<!DOCTYPE html>
<html>
<head>
	<title>Détail de la commande</title>

	<style>
		.order-table th {
			text-align: left;
		}
	</style>

</head>
<body>
	<h1>Détail de la commande n°<?= $_GET['orderId'] ?></h1>

	<section>
		<h2><?= $customer['customerName'] ?></h2>
		<p><?= $customer['contactFirstName'] ?> <?= $customer['contactLastName'] ?></p>
		<p><?= $customer['addressLine1'] ?> <?= $customer['postalCode'] ?> <?= $customer['city'] ?></p>
		<p><?= $customer['country'] ?></p>
	</section>

	<table class="order-table">
		<thead>
			<tr>
				<th>Numéros du produit</th>
				<th>Prix unitaire</th>
				<th>Quantité commandée</th>
				<th>Prix total</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($orderdetails as $detail): ?>
				<tr>
					<td><?= $detail['productName'] ?></td>
					<td><?= number_format($detail['priceEach'], 2, ',', ' ') ?>€</td>
					<td><?= $detail['quantityOrdered'] ?></td>
					<td><?= number_format($detail['total'], 2, ',', ' ') ?>€</td>
				</tr>
			<?php endforeach ?>
		</tbody>
		<tfoot>
			<tr>
				<th colspan="3">Prix HT</th>
				<th><?= number_format($total['totalHT'], 2, ',', ' ') ?>€</th>
			</tr>
			<tr>
				<th colspan="3">Montant TVA</th>
				<th><?= number_format($total['totalTVA'], 2, ',', ' ') ?>€</th>
			</tr>
			<tr>
				<th colspan="3">Prix TTC</th>
				<th><?= number_format($total['totalTTC'], 2, ',', ' ') ?>€</th>
			</tr>
		</tfoot>
	</table>

	<nav>
		<a href="index.php">Retour à la liste des commandes</a>
	</nav>

</body>
</html>