<!DOCTYPE html>
<html>
<head>
	<title>Liste des commandes</title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
	<div class="container">
		<h1>Liste des commandes</h1>

		<nav>
	    	<ul class="pagination">
	    		<li class="page-item<?php if ($currentPage <= 1): ?> disabled<?php endif ?>">
	    			<a class="page-link" href="pagination.php?page=<?= $currentPage - 1 ?>">Précédent</a>
	    		</li>

	    		<?php for ($page = 1; $page <= $totalPages; $page++): ?>
	    			<li class="page-item<?php if ($page === $currentPage): ?> active<?php endif ?>">
	    				<a class="page-link" href="pagination.php?page=<?= $page ?>"><?= $page ?></a>
	    			</li>
	    		<?php endfor ?>

	    		<li class="page-item<?php if ($currentPage >= $totalPages): ?> disabled<?php endif ?>">
	    			<a class="page-link" href="pagination.php?page=<?= $currentPage + 1 ?>">Suivant</a>
	    		</li>
	    	</ul>
	    </nav>

		<main>
			<table class="table table-striped">
		        <thead>
		            <tr>
		                <th>Numéro</th>
		                <th>Date</th>
		                <th>Statut</th>
		                <th>Nom du client</th>
		            </tr>
		        </thead>
		        <tbody>
		        	<?php foreach ($orders as $order): ?>
			            <tr>
			                <td><a href="detail.php?orderId=<?= $order['orderNumber'] ?>"><?= $order['orderNumber'] ?></a></td>
			                <td><?= $order['orderDate'] ?></td>
			                <td><?= $order['status'] ?></td>
			                <td><?= $order['customerName'] ?></td>
			            </tr>
			        <?php endforeach ?>
		        </tbody>
		    </table>
		</main>
	</div>
</body>
</html>